name: Create release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Create release from tag
    runs-on: ubuntu-latest
    steps:
      - name: GIT checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Read version from manifest.json
        run: echo "VERSION=$(grep '"version":' manifest.json | tr --delete '" ,' | sed 's/version://')" >> $GITHUB_OUTPUT
        id: version
      - name: Build changelog since last tag
        id: changelog
        run: |
          git log --oneline $(git describe --tags --abbrev=0 @^)..@ > Changelog.tmp
      - name: Build artifacts
        run: zip -r replywithheader-v${{ steps.version.outputs.VERSION }}.xpi * -x ".*"
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') # Only run for new tags
        with:
          body_path: Changelog.tmp
          files: |
            replywithheader-v${{ steps.version.outputs.VERSION }}.xpi
